### PR TITLE
feature/query-builder/select

### PR DESCRIPTION
**Pull request by edwinmp**
Handles the frontend select operation for the query builder

### CODE REVIEW

**Comment by k8hughes** [comment]
On the Query Step - http://138.68.138.212/queries/build/ a user should be able to save.

Remove "sample output path" field.

When someone clicks save and preview they should be able to go back to the query builder.

On home: you should be able to click the name of the query to open it.  You should also be able to export the data from the home / saved query view.

**Comment by Duncan-Knox** [comment]
Option to remove query on the home page. Maybe under 'actions'.

**Comment by akmiller01** [comment]
Perhaps copy query button for when we have user permissions?

**Comment by edwinmp** [comment]
`Edit Operation` button on Query Data view

**Comment by akmiller01** [comment]
We might need to rethink the audit log. It looks like POSTs aren't recording the user faithfully:

image

**Comment by akmiller01** [comment]
@edwinmp adding more sources now. Looks like we could use a "Next page" button for sources, as well as removing "()" when no acronym exists.

image

**Comment by edwinmp** [comment]
@akmiller01 yeah, on the View Data page as well... postponed adding pagination though... Will do that as part of clean up and enhancements. Made a note of it. Good catch on the acronyms... 👍

**Review by akmiller01 — APPROVED** [review]
Working well! :shipit:

**Pull request merged**
