### PR TITLE
Feature/query builder/aggregate

### PR DESCRIPTION
**Pull request by edwinmp**
Contains:

- [New] Aggregate (issue #39)
- [New] Transform (Scalar & Multi) - issue #44 #37  
- [New] Join - issue #36 
- [Update] add pagination to data sources
- [Update] add pagination to operation data
- [New] operations that result in custom columns, these columns are always shown in the results
- [Update] add pagination to data sources
- [New] add Export to CSV for operation data - issue #41 
- [Update] format original column names for use as captions
- [New] reset button on query builder

### CODE REVIEW

**Comment by Duncan-Knox** [comment]
Adding secondary filter on 'create operation step' to an existing operation with a filter seems to function differently to adding a (second) filter to a new operation step. The former does not seem to apply both filters. The latter does, which is preferable as it allows the user to use two filters to create a between operation. This is not a significant issue but may cause confusion.

**Comment by Duncan-Knox** [comment]
Query Data: is it possible at all to increase the number of columns the user can view on 'view data'?

**Comment by edwinmp** [comment]
> Adding secondary filter on 'create operation step' to an existing operation with a filter seems to function differently to adding a (second) filter to a new operation step. The former does not seem to apply both filters. The latter does, which is preferable as it allows the user to use two filters to create a between operation. This is not a significant issue but may cause confusion.

Correct me if I'm wrong, @akmiller01 ... multiple filter options on the same step translate as an `OR` operation (rows that match one of them are returned), while adding multiple filter steps on an operation translates as an `AND` (rows that match both are returned). We'll need to add documentation/help that explains this.

**Comment by edwinmp** [comment]
> Query Data: is it possible at all to increase the number of columns the user can view on 'view data'?

Not at the moment. They're hardcoded to 6. Now that I've added the `Select`, I'll show all columns. Will be up to the user to use the `Select` operation to limit how many are shown.

**Comment by Duncan-Knox** [comment]
> > Adding secondary filter on 'create operation step' to an existing operation with a filter seems to function differently to adding a (second) filter to a new operation step. The former does not seem to apply both filters. The latter does, which is preferable as it allows the user to use two filters to create a between operation. This is not a significant issue but may cause confusion.
> 
> Correct me if I'm wrong, @akmiller01 ... multiple filter options on the same step translate as an `OR` operation (rows that match one of them are returned), while adding multiple filter steps on an operation translates as an `AND` (rows that match both are returned). We'll need to add documentation/help that explains this.

Thanks @edwinmp , I should have seen it this way. This makes sense and sounds very useful to have this set-up.

**Review by akmiller01 — APPROVED** [review]
Bugs seem to be fixed!

**Pull request merged**
