### PR TITLE
Feature/docker development

### PR DESCRIPTION
**Pull request by wakibi**

### CODE REVIEW

**Comment by akmiller01** [comment]
Just checking with @davidebukali is cron run inside the Docker or outside of it?

**Comment by wakibi** [comment]
@akmiller01 it's run inside the Docker

**Comment by akmiller01** [comment]
The docker build failed. Does cron have some dependencies we're missing?
```
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get install cron' returned a non-zero code: 1
```

**Comment by wakibi** [comment]
@akmiller01 kindly review again at the earliest. I had missed the -y flag on that command

**Review by akmiller01 — APPROVED** [review]

**Pull request merged**
