### PR TITLE
Feature | Multiple Joins

### PR DESCRIPTION
**Pull request by davidebukali**
Add multiple joins to the advanced query builder #591

### CODE REVIEW

**Review by edwinmp — CHANGES_REQUESTED** [review]
There's more than a few behavioural bugs. Test better. Proper testing is NOT just using it as expected ... users don't behave that way.

Here's the issues I found

1. I have to click `Add` or `Edit` to update the join config - I found this a UX hustle. I press the plus button, it tells me the mapping has been added - that's all I need.
2. It's not clear how to add multiple mappings for the same table - I figured it out by mistake. So like the basic join, use multiple rows for each new mapping - I don't mind if you have to reuse that view, complete with the whole `Add mapping` button ... it's clearer & our users are already used to it.
3. The select columns widget is buggy ... for one, it seems to be tied to its twin under the `Select` query. So when the select query is set to `Select all`, the one in the join has `Select columns for Ordering`. Order columns hasn't worked once ... if it's not disabled, it just doesn't have the expected columns (I think it's taking from the `Select` config). Clear/reset does nothing as far as I can tell. If you want to customise this component for reuse, be sure it's fully customisable ... e.g besides all the above, it'd be nice to have a custom button caption like `Select Join Columns` or something. Also, joins don't require columns from the joined table to work so not having any selected shouldn't keep the `Add` button disabled. A mapping is all that's required.
4. Delete a join and then try to add a new one ... fails.
5. There's a strange delay to update the preview (any of them), For the config preview, I have to click on it for the changes to show. I'm not sure this is only on your join or caused by it.
6. Remove the icon on the `View joins` buttons
7. It's confusing having actions all over the place ... like the `Select`, I'd rather they're all in a single ButtonGroup (including the mapping & delete) - not important for now, so don't mind it - can improve later (behaviour first).
8. Can't seen to add more than one join ... the `Add` button never seems to light up the second time around. And then it magically lit up when I scrolled through the configs (maybe I clicked the editor)

**Comment by wakibi** [comment]
@davidebukali is this ready for review? I see you pushed more changes after the last changes were requested

**Comment by davidebukali** [comment]
@wakibi its not ready for review, am working on the feedback

**Comment by davidebukali** [comment]
@edwinmp and @wakibi this includes feedback for issues 1,2,4 and 8 mentioned in the comment above; From the pending issues, I think 3 would  require most work, while the rest are more likely simple edits.

**Comment by edwinmp** [comment]
@davidebukali create a beta release so this can be tested on staging

**Comment by edwinmp** [comment]
Since yours is the incoming PR, could you please generate migrations & commit - there's a package update that requires it.

**Comment by edwinmp** [comment]
@davidebukali could you please sort the failing e2e test as well ... it's just the one so it's probably nothing serious.

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
