### PR TITLE
Whitelist iati publishers table

### PR DESCRIPTION
**Pull request by akmiller01**

### CODE REVIEW

**Review by edwinmp — DISMISSED** [review]

**Comment by k8hughes** [comment]
Can this be merged?

**Comment by akmiller01** [comment]
> Can this be merged?

We're waiting on the IATI publisher table columns to be updated by Dean, but he's busy with the GNR right now.

**Comment by k8hughes** [comment]
ah OK, makes sense

**Comment by k8hughes** [comment]
@akmiller01  what is the status of this issue?  Did it get merged the other week?

**Comment by akmiller01** [comment]
> @akmiller01 what is the status of this issue? Did it get merged the other week?

Just updated it with the base branch. It still needs to be merged.

**Comment by k8hughes** [comment]
Is there someone that needs to be tagged for review or who will merge it?

**Comment by akmiller01** [comment]
> Is there someone that needs to be tagged for review or who will merge it?

Yep. Re-requested a review from Edwin when I made the change. I'll tag the rest of the devs too.

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
