### PR TITLE
Added indexing to common name fields in repo

### PR DESCRIPTION
**Pull request by Napho**
Added index to crs and dac tables to fix issue of failure on complex search

### CODE REVIEW

**Review by akmiller01 — DISMISSED** [review]
Lookin' good.

**Comment by akmiller01** [comment]
@Napho Gave `completed_scripts.sh` a full run locally. I think the new R code failed:

```
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  data type text has no default operator class for access method "gin"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.
)
Calls: dbSendQuery -> dbSendQuery -> postgresqlExecStatement -> .Call
Execution halted
```

Going to try and troubleshoot tonight.

**Comment by Napho** [comment]
@Alex, I know the error, it just means the installation of gin hasn't succeeded. I'm guessing the pg_catalog but happy to look at it tomorrow

**Comment by Napho** [comment]
The update query on pg_class is meant to solve that, query is in dba.sql

**Comment by akmiller01** [comment]
When is the entrypoint meant to be run? We need to remove the `drop database analyst_ui` part from dba.sql if it's meant to be run on each rebuild.

**Comment by akmiller01** [comment]
Answered my own question. It requires the volume to be empty: https://stackoverflow.com/a/39765233

**Review by akmiller01 — APPROVED** [review]
Okay, after a full run, just WDI was missing the `here` package. I think all is working well from a blank slate volume now.

**Pull request merged**
