### PR TITLE
Feature | Move push_folder_to_github method to the utils.py

### PR DESCRIPTION
**Pull request by pauline-n**
#704

### CODE REVIEW

**Review by ThatcherK — DISMISSED** [review]
Looks okay

**Comment by ThatcherK** [comment]
This has to be tested on staging before we merge it

**Comment by edwinmp** [comment]
> This has to be tested on staging before we merge it

@ThatcherK could you take @pauline-n through how to do this

**Comment by ThatcherK** [comment]
@edwinmp yes, that's what I intend to do

**Comment by edwinmp** [comment]
@ThatcherK @pauline-n what's the update on this? Want to push a release today & need to know if this will be ready for it

**Comment by ThatcherK** [comment]
@edwinmp Let me work on this with @pauline-n  after standup...

**Review by ThatcherK — APPROVED** [review]

**Pull request merged**
