### PR TITLE
Feature | Sub Query

### PR DESCRIPTION
**Pull request by edwinmp**

### CODE REVIEW

**Comment by k8hughes** [comment]
@wakibi can you take a look at this before picking up anything new

**Comment by k8hughes** [comment]
@akmiller01  can you review this this week so we can merge it?

**Comment by akmiller01** [comment]
@wakibi was this ever tested on staging?

**Comment by wakibi** [comment]
> @wakibi was this ever tested on staging?

Yes it was, around the time we had that slack discussion about Django Migrations acting up. Rebasing it and having another go at it will not hurt though. Will spare some time for it tomorrow or Friday.

**Comment by k8hughes** [comment]
@wakibi  can you look at this before Easter.

**Comment by wakibi** [comment]
> > @wakibi was this ever tested on staging?
> 
> Yes it was, around the time we had that slack discussion about Django Migrations acting up. Rebasing it and having another go at it will not hurt though. Will spare some time for it tomorrow or Friday.

Quick update, this is still breaking some queries, particularly those that use **aggregate** functions. Working to fix them.

**Comment by k8hughes** [comment]
@wakibi where has this got to in the end?  Could you put and update on here with the next steps please?

**Comment by wakibi** [comment]
Lot's of changes on the QueryBuilder, which has affected the tests. So I am re-writing all tests for the QB, that's the final step

**Comment by akmiller01** [comment]
> Lot's of changes on the QueryBuilder, which has affected the tests. So I am re-writing all tests for the QB, that's the final step

Hi Chris, could you also delete any migrations this created, rebase with the develop migrations, and then re-make migrations? That way we can ensure all the migrations are in sync. The migrations in develop were pulled from production.

**Comment by wakibi** [comment]
@akmiller01 thanks for the heads up.

**Comment by wakibi** [comment]
@akmiller01 please approve this once you are done testing. Cheers

**Comment by akmiller01** [comment]
@wakibi I've done all the local and staging testing that I can. But why are we developing the backend of this feature separately from the frontend? Now that the backend is done, does it make sense to first develop the frontend into this branch before the feature makes it into develop so we can test the new functionality? @edwinmp

**Comment by edwinmp** [comment]
> @wakibi I've done all the local and staging testing that I can. But why are we developing the backend of this feature separately from the frontend? Now that the backend is done, does it make sense to first develop the frontend into this branch before the feature makes it into develop so we can test the new functionality? @edwinmp

Yes, that would be best ... will can create a FE branch off this one to ease reviews.

**Comment by wakibi** [comment]
Great. In that case I will cherry-pick the commits that fix the error pointed out in #260

**Comment by k8hughes** [comment]
Do we still have code to merge from this?

**Pull request closed without merging**
