### PR TITLE
Feature/email notifications

### PR DESCRIPTION
**Pull request by davidebukali**
Send email notification to users in 'ADMINS=[]' setting variable when a scheduled event has run for too long or failed; More details #316

### CODE REVIEW

**Comment by akmiller01** [comment]
Hi @davidebukali , just testing this out now.

Do I need to fill out these alert fields in order for this to work?
image

It might be easier to have the alert messages be programmatically determined from the scheduled event name, and the type of error that happened.

**Comment by davidebukali** [comment]
@akmiller01 I agree its easier to create the message programmatically, maybe scrap the `Alert` class and send mail from the `ScheduledEvent` class; what do you think ?

**Comment by akmiller01** [comment]
> @akmiller01 I agree its easier to create the message programmatically, maybe scrap the `Alert` class and send mail from the `ScheduledEvent` class; what do you think ?

Yes that sounds like a good way of handling it!

**Comment by davidebukali** [comment]
@akmiller01 emails are now created programmatically from the `scheduled_event` using `script_name` and error that occured

**Review by akmiller01 — APPROVED** [review]
Looks good, David!

**Pull request merged**
