### PR TITLE
Fix/pypika joins

### PR DESCRIPTION
**Pull request by akmiller01**
Fixes Pypika step ordering

Changes join behavior to alias columns in common between Table1 and Table2.

### CODE REVIEW

**Comment by edwinmp** [comment]
@akmiller01 added the FE changes for this...

**Comment by akmiller01** [comment]
@edwinmp just gave this a test. Are you able to add to the dropdown the columns which result from a join?

For e.g. if you take CRS and join CRS_isos, you would expect in the next step that ISO3 would be a column on the left-hand dropdown for future joins:

image

In other words, the new state of the columns should be the union of the columns from previous joins.

**Comment by edwinmp** [comment]
@akmiller01 not yet ... I'm not yet executing each step as it's saved. The screenshot is showing an old view of the join operation though... please pull.

**Comment by akmiller01** [comment]
You don't need to execute a step to know the columns from a join. You could store the state of the columns at any given step as the union of all joined datasets columns up to that point http://2ality.com/2015/01/es6-set-operations.html

**Comment by akmiller01** [comment]
I think this is ready to merge @edwinmp Just did a pretty complicated test.

1. Join ISOS to CRS
2. Aggregate ISOS by CRS and Year
3. Join aggregated CRS to country income groups by ISO and year

Worked flawlessly

image

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
