### PR TITLE
Participating org refactor

### PR DESCRIPTION
**Pull request by akmiller01**
Discussion: https://github.com/devinit/ddw-analyst-ui/discussions/389

Issue: https://github.com/devinit/ddw-analyst-ui/issues/395

### CODE REVIEW

**Comment by edwinmp** [comment]
@akmiller01 reverting `develop` messed up the history here.

**Comment by akmiller01** [comment]
> @akmiller01 reverting `develop` messed up the history here.

Okay, I'll try and cherry-pick it. Some aspects of this are still under discussion here https://github.com/devinit/ddw-analyst-ui/discussions/389

**Comment by wakibi** [comment]
@akmiller01 you will have to push the CSVs to [this](https://github.com/devinit/ddw-data-update-configs) repo and rebase against develop for latest changes.

**Comment by akmiller01** [comment]
Columns also added to this PR: https://github.com/devinit/ddw-data-update-configs/pull/3

**Review by wakibi — APPROVED** [review]
Looks good!

**Pull request merged**
