### PR TITLE
Refactor of IATI recipient columns

### PR DESCRIPTION
**Pull request by akmiller01**

### CODE REVIEW

**Comment by k8hughes** [comment]
@akmiller01 whats the plan with this PR?

**Comment by akmiller01** [comment]
> @akmiller01 whats the plan with this PR?

It was a feature requested in a Slack message, but the discussion around it got side-tracked by discussion about indexing: https://devinitorg.slack.com/archives/C9EU5RYAE/p1602772963005000

Probably still worth re-adding the region vocabulary, but I imagine removing x_country variables would break quite a few queries now.

**Comment by akmiller01** [comment]
Dependent on new columns here: https://github.com/devinit/ddw-data-update-configs/pull/3

**Comment by wakibi** [comment]
@akmiller01 kindly rebase against current develop branch and I shall review this. There are conflicts

**Review by wakibi — APPROVED** [review]
LGTM!

**Pull request merged**
