### PR TITLE
Feature/main-layout

### PR DESCRIPTION
**Pull request by edwinmp**
Opted for a sidebar as our main navigation component. It's retractable so no worries about space.

### CODE REVIEW

**Review by akmiller01 — DISMISSED** [review]
Looks good! 
image

**Comment by edwinmp** [comment]
Ah, thanks for reminding me of this feature on small devices. That background should not be black ... and the logout options isn't available in this view. Let me add those.

**Review by akmiller01 — DISMISSED** [review]
Looking food! I still had to edit my `settings.py` to get it to migrate, but hopefully the setup will be fixed in #56 

image

**Review by akmiller01 — APPROVED** [review]
Yep! Looking good!

**Pull request merged**
