### PR TITLE
IATI ETL Updates

### PR DESCRIPTION
**Pull request by akmiller01**

### CODE REVIEW

**Comment by akmiller01** [comment]
Note to self. Remove `index iati_id_btree_idx on repo.iati_transactions` before re-indexing.

**Comment by wakibi** [comment]
Did we agree on the indexing fields here?

**Comment by akmiller01** [comment]
Through a few Slack threads. Happy to discuss the pros/cons of doing it
here, or indexing different fields!

**Review by wakibi — APPROVED** [review]
Managed to look up the slack conversations. Cheers

**Pull request merged**
