### PR TITLE
Feature/Replace Jquery Query Builder With React Query Builder

### PR DESCRIPTION
**Pull request by ThatcherK**
ticket #658 
Replace the query builder in both having and filter advancedQueryBuilder

### CODE REVIEW

**Comment by ThatcherK** [comment]
@edwinmp  ready for review

**Comment by edwinmp** [comment]
> @edwinmp ready for review

@davidebukali to review

**Review by davidebukali — COMMENTED** [review]
`contains` operator shows invalid error in the UI

**Comment by ThatcherK** [comment]
ready for review

**Review by edwinmp — COMMENTED** [review]
@ThatcherK I can't save new queries ... I press save, nothing happens ... not sure if it's just me, so do verify.

**Comment by ThatcherK** [comment]
@edwinmp , my queries are saved just fine. Not experiencing the same here

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
