### PR TITLE
Feature/sub query

### PR DESCRIPTION
**Pull request by wakibi**

### CODE REVIEW

**Comment by akmiller01** [comment]
Could you check why tests are failing on this PR @wakibi ?

**Comment by wakibi** [comment]
> Could you check why tests are failing on this PR @wakibi ?

It's to do with the new **is_sub_query** field I added to the operation model I believe. Will look it further and let you know.

**Comment by wakibi** [comment]
@akmiller01 tests running fine now.

**Comment by k8hughes** [comment]
@akmiller01 could you review this when you have time?

**Comment by akmiller01** [comment]
Could you resolve the branch conflicts @wakibi ?

**Comment by k8hughes** [comment]
@wakibi can you take a look at the comments from Alex?

**Comment by k8hughes** [comment]
@edwinmp when you have time do you want to review this?  Will you do the FE on the same branch or on a new branch?

**Comment by edwinmp** [comment]
@k8hughes I'm on it today ... will merge it in when done and do the FE in a different branch

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
