### PR TITLE
Feature | Advanced QB Filter Updates

### PR DESCRIPTION
**Pull request by davidebukali**
Updates for advanced query builder filters #531

### CODE REVIEW

**Review by edwinmp — CHANGES_REQUESTED** [review]
Good work on this.

image

There's an `x` that doesn't do anything ... that's a close button, so I hope you weren't using it as an error indicator ... convention makes us want to click it ... it's fine to simply remove it.

Rename the error message to `The operator $e is invalid` ... since we can have multiple configs for the same column, doesn't help much to mention it. In a later iteration of this, we shall be able to show these errors directly in the editor.

image

Finally, the requirement was for ONLY the value to be reset on adding a new filter ... by value, I meant he `value` field. This is reseting the whole thing.

**Comment by edwinmp** [comment]
@davidebukali 

We need to make sure that the added filter config actually has something to filter. Currently, you can add a filter that's an empty array ... shouldn't be allowed

I've realised we are going to need on more button ... the `Remove/Clear` button ... sounds similar to reset but this one removes filter configs from the main JSON. i.e. the entire config is removed, even the `filter` property.

**Comment by davidebukali** [comment]
@edwinmp added a clear button below the main JSON to remove all filters and included validation to prevent adding a filter without all values set.

**Comment by edwinmp** [comment]
@davidebukali what's the hold up with this one?

**Pull request merged**
