### PR TITLE
feature/login

### PR DESCRIPTION
**Pull request by edwinmp**
- [x] Local Login
- [ ] Google Login

### CODE REVIEW

**Review by akmiller01 — DISMISSED** [review]
Looks good. Would it be worth looking into adding tests with CI @edwinmp ? Maybe I can help with that next week.

**Comment by edwinmp** [comment]
@akmiller01 have set up travis to run unit tests, though only successfully for the JS tests. Tried to run `python` tests today, but they only run successfully within the `docker` container (only locally). It's failing on travis. Will continue looking into it tomorrow. Also going to start on the end-to-end tests tomorrow.

**Review by akmiller01 — DISMISSED** [review]

**Review by akmiller01 — APPROVED** [review]
Looks good! We may want to consider removing some of the hanging dependencies if we don't end up going the social route.

**Comment by edwinmp** [comment]
True ... will put a deadline on it.

**Pull request merged**
