### PR TITLE
Fix | Disappearing Filter Value

### PR DESCRIPTION
**Pull request by ThatcherK**
Ticket #899

### CODE REVIEW

**Comment by edwinmp** [comment]
@ThatcherK create a beta release and let me know when its ready for testing on staging.

**Comment by edwinmp** [comment]
@ThatcherK either the deployment isn't reflecting or this bug isn't fixed. Still getting it on staging.

**Comment by ThatcherK** [comment]
@edwinmp , I had errors in the deployment run, so its not yet on staging

**Comment by ThatcherK** [comment]
@edwinmp  this is now on staging, you can now test

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
