### PR TITLE
Feature/ui/query-builder

### PR DESCRIPTION
**Pull request by edwinmp**

### CODE REVIEW

**Comment by edwinmp** [comment]
I've decided to postpone writing unit tests ... shall do it after I have a stable release out for testing.

**Comment by akmiller01** [comment]
@edwinmp are you pointing to any endpoints without an ending slash? It's causing a small redirect on each page load:
```
[02/Apr/2019 13:44:19] "GET /api/users/1 HTTP/1.1" 301 0
[02/Apr/2019 13:44:19] "GET /api/users/1/ HTTP/1.1" 200 116
```

**Comment by edwinmp** [comment]
> @edwinmp are you pointing to any endpoints without an ending slash? It's causing a small redirect on each page load:
> 
> ```
> [02/Apr/2019 13:44:19] "GET /api/users/1 HTTP/1.1" 301 0
> [02/Apr/2019 13:44:19] "GET /api/users/1/ HTTP/1.1" 200 116
> ```

Had some trouble with that... thought it was only for some URLs... will fix for all.

**Comment by akmiller01** [comment]
Minor graphical glitch. It looks like all operation_steps of a certain type highlight when you click one? In this case two filters:
image

**Comment by akmiller01** [comment]
Hm, and I may need to see whether this is an issue with how the UI is posting an update to operationstep, but it seems like creating new steps automatically delete the first one.

**Comment by akmiller01** [comment]
Are you posting the Operations with all of it's existing steps, or just the updated ones @edwinmp ? If you just post the updated steps, these lines https://github.com/devinit/ddw-analyst-ui/blob/feature/ui/query-builder/core/serializers.py#L143-L145 will delete any steps that were in the original Operation and not re-posted.

**Comment by edwinmp** [comment]
> Minor graphical glitch. It looks like all operation_steps of a certain type highlight when you click one? In this case two filters:
> image

I'm curious how you arrived at this one. Was it while creating a new operation or editing an existing one? Either way, I couldn't replicate it. It's not new, but I thought I'd fixed it. Hope you've pulled all the latests updates to the branch.

**Comment by edwinmp** [comment]
> Are you posting the Operations with all of it's existing steps, or just the updated ones @edwinmp ? If you just post the updated steps, these lines https://github.com/devinit/ddw-analyst-ui/blob/feature/ui/query-builder/core/serializers.py#L143-L145 will delete any steps that were in the original Operation and not re-posted.

@akmiller01 I update the entire operation, with all the steps.

**Comment by akmiller01** [comment]
The double highlight happens every time when I edit an existing Operation, click to add a new Step, and then save it. During the edit of the new Step, the previous step is highlighted. And then they both get highlighted after clicking Save.

image

**Comment by akmiller01** [comment]
Actually, the double-highlight might also explain why some steps go missing after save. The step ID is not being incremented so I end up with multiple steps with the same ID.

**Review by akmiller01 — APPROVED** [review]
Python bits look good! I'll go ahead and deploy this to staging

**Pull request merged**
